### ISSUE TITLE
SAS Viya 4 - logging & monitoring - how to shutdown?

### ISSUE THREAD

**Issue by ken-sys** [sassoftware/viya4-monitoring-kubernetes#129]
SAS Viya 4 - logging & monitoring - how to shutdown?

Problem Description:
   I did try this, but I think there's some missing steps.  They're  still up.

[root@server ~]# kubectl -n monitoring scale deployment v4m-grafana --replicas=0
deployment.apps/v4m-grafana scaled
[root@server ~]# kubectl -n monitoring scale deployment v4m-kube-state-metrics --replicas=0
deployment.apps/v4m-kube-state-metrics scaled
[root@server ~]# kubectl -n monitoring scale deployment v4m-operator --replicas=0
deployment.apps/v4m-operator scaled
[root@server ~]# kubectl -n logging scale deployment v4m-es-kibana --replicas=0
deployment.apps/v4m-es-kibana scaled
[root@server ~]# kubectl -n logging scale deployment v4m-es-exporter --replicas=0
deployment.apps/v4m-es-exporter scaled
[root@server ~]# kubectl -n logging scale deployment v4m-es-client --replicas=0
deployment.apps/v4m-es-client scaled

**Comment by gsmith-sas** [comment]
@ken-sys  Although we're deploying Elasticsearch and Kibana within Kubernetes, neither application can be scaled using the _kubectl scale_ commands.  This is due to the pre-cloud architecture of Elasticsearch.  As you scale down the number of Elasticsearch pods, it scrambles to redistribute the indexes (stored data) on the remaining pods.  Even if all the pods are shut-down, the data store would be corrupted/unusable and you would not have a working instance when you scaled back up.  

Some of our colleagues who maintain internal testing or training clusters have used a remove and redeploy process for handing this sort of need.  Rather than scaling down (using _kubectl scale_ commands), they run the removal script (_remove_logging_open.sh_).  It is important to leave the namespace and the associated PVCs in place.  If that's been done, when you run the deployment script (_deploy_logging_open.sh_) to redeploy the logging components, the existing PVCs are reused.  This means any data or content that existed when you shutdown are still there when you redeploy.  While not strictly a scale down/up process the result is the same.  Perhaps this approach will work in your use-case as well.
