### ISSUE TITLE
azure sample "user-values-elasticsearch-open.yaml" makes the logging framework installation fail

### ISSUE THREAD

**Issue by raphaelpoumarede** [sassoftware/viya4-monitoring-kubernetes#157]
Hi there, I'm deploying the logging framework in azure and when I use the provided Azure [sample ](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/d50c4f9e78cc3f7790600da1a3976df92383b8ed/samples/azure-deployment/logging/user-values-elasticsearch-open.yaml)(with a path-based ingress).

It use to work but now the setup fails with the message below:

```sh
Successfully packaged chart and saved it to: /tmp/sas.mon.1kETJF7q/opendistro-build/helm/opendistro-es/opendistro-es-1.8.0.tgz
Release "odfe" does not exist. Installing it now.
Error: Ingress.extensions "v4m-es-kibana" is invalid: metadata.annotations: Invalid value: "nginx.ingress.kubernetes.io configuration-snippet": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')
```

If I remove the nginx.ingress.kubernetes.io configuration-snippet, the setup is successful but I can not reach the Kibana web page.
I'm using the `1.0.9` release.

Thanks for your help !

**Comment by BryanEllington** [comment]
The key in the [sample](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/d50c4f9e78cc3f7790600da1a3976df92383b8ed/samples/azure-deployment/logging/user-values-elasticsearch-open.yaml#L39) is "nginx.ingress.kubernetes.io/configuration-snippet". Above, it appears you have a space instead of the forward slash.

If you still have a problem, please include the user-values-elasticsearch-open.yaml (or at least the ingres: section), if possible.

**Comment by raphaelpoumarede** [comment]
Good catch Bryan ! thanks for the quick turnaround ! 
it is working now, I don't know why/how the "/" was removed.
Cheers
