### ISSUE TITLE
Upgrade instruction 

### ISSUE THREAD

**Issue by sangram23** [sassoftware/viya4-monitoring-kubernetes#326]
Hi Team,
We are planning the to upgrade our existing viya monitoring and logging component. Is there any instruction to upgrade? We have some customization like path based routing , slack alert we don't want to loose these settings.

**Comment by sangram23** [comment]
could you please provide instruction  ?

**Comment by gsmith-sas** [comment]
Helllo @sangram23 ,

  Our deployment scripts are designed to be re-runnable and, when re-run, should upgrade components as needed. To ensure customizations (such as configuring path-based ingress) are maintained, it is _critically_ important to ensure you have the **USER_DIR** environment variable to the same location that you used originally (and which contain the files defining those customizations). The collected data (logs and metrics) should remain available after the upgrade since the existing PVCs (storage) will be reused. If you have manually expanded the size of any of the PVCs (following the instructions in **[Log_Retention.md](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/master/logging/Log_Retention.md)**, for example), be sure to update the information in the corresponding .yaml file in your USER_DIR, if you haven't done that already. If you don't, there's a good chance you will end up losing data. Similarly, you would also want to make sure the **LOG_RETENTION_PERIOD** variable (in the **$USER_DIR/logging/user.env** file) has been updated to match your current log retention period.  Other than that, we would discourage you from making any new tweaks/customizations during the upgrade.

  You should just re-run the deployment scripts (e.g. **deploy_monitoring_cluster.sh**, **deploy_logging_open.sh**, etc.). You should NOT run the removal scripts (e.g. **remove_monitoring_cluster.sh**, **remove_logging_open.sh**). As always, we encourage you do update your copy of the project repository and use the code from the 'stable' branch. Be sure the review the **[CHANGELOG.md](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/master/CHANGELOG.md)** for information on any breaking changes that might have been introduced since you deployed originally.  We generally publish new releases monthly, so be sure to review the notes for all releases since you last deployed.

  I do not know how you have implemented "slack alerts" but I believe those should be fine since they are probably persisted in the same storage layers as the metrics or logs. But, having said that, I would encourage you to document all of those things in case something goes wrong and you need to re-create them. Similarly, if you have created any new Kibana content (e.g. dashboards, visualizations or saved queries), you should probably export those items to a file as well. They should be fine during an upgrade but, if something does go wrong during the upgrade, you could import them back into Kibana afterwards, if need be. Exporting and importing Kibana content are options available on the **Saved Objects** page within the Stack Management panel of Kibana.

  Finally, I wanted to let you know that we expect to publish a new release tomorrow evening. So, you may want to wait for that to ensure you have the latest updates.
