### ISSUE TITLE
postgreSQL dashboard not showing namespace choice.

### ISSUE THREAD

**Issue by dikpater** [sassoftware/viya4-monitoring-kubernetes#328]
We have 2 namespaces of viya4 in 1 cluster.
For PostgreSQL I cannot choose the namespace.
For PostgreSQL database I also cannot choose thenamespace, but I can choose 2 instanceid's .

How can I solve this ?

Regards, 

Dik Pater

**Comment by gsmith-sas** [comment]
Thank you  for reporting these issues.

### Dashboard: PostgreSQL Dashboard
For the issue with the **PostgreSQL Dashboard** , a small change to the dashboard definition is needed to get the NAMESPACE pulldown working.  We will fix this in an upcoming release, but, in the meantime, you can fix things in your environment by doing the following:

- Sign into Grafana and bring up the **PostgreSQL Dashboard**
- Click on the "gear" icon in the upper right to open the "**_Dashboard Settings_**" panel
- Click on the **_Variables_** link on the menu along the left side
- Click on **namespace** in the list of variables displayed
- In the **_Regex_** field (in the **_Query Options_** section), change the text from `/.*kubernetes_namespace="([^"]+).*/` to `/.*namespace="([^"]+).*/`
- Click on the **_Update_** button

Since the **PostgreSQL Dashboard** dashboard is an auto-provisioned dashboard, you will not be able to save the updated dashboard.  However, you can save the updated dashboard under a new name.  To do that, 
- Click on the **_Save As..._** link on the left
- Provide a new name e.g. **PostgreSQL Dashboard (Updated)**
- Click on the **_Save_** button

### Dashboard: PostgreSQL 
The issue with the **PostgreSQL** dashboard will require some further thought/discussion as we decide if/how we want to revise that dashboard.

We hope that helps.  Please let us know how it goes.

**Comment by gsmith-sas** [comment]
@dikpater  We updated the two Postgres-focused Grafana dashboards with our latest update (version 1.2.0) released earlier this week.  You can update your deployment to pick up all of the latest updates by re-running the deploy_monitoring_cluster.sh and deploy_monitoring_viya.sh scripts.  Or, if you prefer, you can manually update one or both these dashboards by running the deploy_dashboards.sh script and pointing to the updated JSON files.  The two JSON files are: **monitoring/dashboards/pgmonitor/pg-details.json** and **monitoring/dashboards/viya/postgres-dashboard.json**.  But don't forget to to re-clone the project repo (or update your existing copy of the repo) to pick up our latest updates and then checkout the "stable" branch before running any of the scripts.

**Comment by dikpater** [comment]
Greg
Thank you very much.
I Will try this as soon as possible!

Dank je wel!
Dik

Op do 16 jun. 2022 om 21:01 schreef Greg Smith ***@***.***>

**Comment by dikpater** [comment]
We have not the right kubernetes version on our server. I asked the kube team when it is upgraded.
I have a question  I see $prometheus now.
I used this : sed -i 's?"datasource": "$datasource"?"datasource": "Prometheus"?' *.json
But in the README.MD there is the old variable ?
Second question : can I use the postgres dashboard with our kubernetes version  v1.20.15 ?
Regards,

Dik Pater.
