### ISSUE TITLE
Documentation issue in logging readme

### ISSUE THREAD

**Issue by autphm** [sassoftware/viya4-monitoring-kubernetes#33]
Logging readme.md mentions a NODE_PLACEMENT_ENABLE variable that does not work / exist.
Looks like this should read LOG_NODE_PLACEMENT_ENABLE as this variable is used in .sh scripts.

**Comment by gsmith-sas** [comment]
Thank you for providing feedback.
The **LOG_NODE_PLACEMENT_ENABLE** environment variable can be used if you only want to enable/disable node place for the pods containing the logging components.  There is a similar environment variable, **MON_NODE_PLACEMENT_ENABLE**, impacting the pods containing the monitoring components.  However, since we suspect users will generally want to handle things consistently across logging and monitoring, we also support the **NODE_PLACEMENT_ENABLE** environment variable.  If either of the other two environment variables are not set explicitly, they are set to the value of this top-level environment variable.

So, setting **NODE_PLACEMENT_ENABLE** _should_ have worked.  Can you provide more information on why you believe setting this environment variable did not work for you? Did you checkout a specific release/tag or were you working on the  MASTER branch?

**Comment by gsmith-sas** [comment]
Communicated with autphm off-line and he confirmed he had overlooked the line in the logging/bin/deploy_logging_open.sh script where we use the value of NODE_PLACEMENT_ENABLE to set LOG_NODE_PLACEMENT_ENABLE if it is not explicitly set.  Closing issue.
