### ISSUE TITLE
Set the maximum log retention period beyond one month

### ISSUE THREAD

**Issue by irchum** [sassoftware/viya4-monitoring-kubernetes#383]
Hi All,

I'm Ira, a member SAS Technical Support. A customer is asking whether it is possible to increase the maximum log retention period to beyond one month. If yes, how can it be done?

According to SAS PSD, "the customer will need log retention of more than 1 month because we are implementing complex processes under Viya 4 where 1700 users will be triggering logging jobs. The production start-up is done on a very tight schedule and we will need to follow the jobs launched in a precise manner and eventually go back to the logs history."

Thank you

Regards,
Ira

**Comment by gsmith-sas** [comment]
@irchum  We provide information about how to adjust the log retention period in the [Log_Retention.md](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/main/logging/Log_Retention.md) document in the logging sub-directory of our repo.

However, as mentioned in that document, we would _**strongly discourage**_ customers from extending the log retention period to such a long period.  SAS Viya can generate a large number of log messages especially given the user population you mention.  Our monitoring solution is intended to help admins monitor _on a day-to-day basis_ their health of their running SAS Viya system.  I'm not sure maintaining logs for 30 days really fits that use-case.   For example, our solution keeps all of the log messages collected during the entire retention period in memory at all times.  Doing that for 30 days would consume a huge amount of memory and most likely require additional OpenSearch nodes (over the 3 we deploy by default) to be deployed.

I am going to close this issue here and will follow-up with you via internal e-mail to discuss further.
