### ISSUE TITLE
Viya LTS 2022.1 (AWS) -  Scheduling problem for Viya Monitoring pods

### ISSUE THREAD

**Issue by irchum** [sassoftware/viya4-monitoring-kubernetes#397]
Hi Team,

A SAS PSD engineer has opened a ticket with SAS Technical Support:

Viya has been deployed on AWS using [Viya deployment project](https://github.com/sassoftware/viya4-deployment). 
`viya4-deployment --tags "baseline,viya,cluster-logging,cluster-monitoring,viya-monitoring,install"`

viya-monitoring has also been deployed along with it.

On AWS, we have to scale-down the nodes in the AWS EKS cluster to stop the cluster. After restarting the EKS cluster, we have encountered the following problem:
Viya Monitoring is no longer operational. We think that this is due to the corruption of the data store as mentioned here (https://github.com/sassoftware/viya4-monitoring-kubernetes/issues/129)

The potential solution, according to the above link, is to use a remove and redeploy process. 
A comment on this issue says, “Rather than scaling down (using kubectl scale commands), they run the removal script (remove_logging_open.sh). It is important to leave the namespace and the associated PVCs in place. If that's been done, when you run the deployment script (deploy_logging_open.sh) to redeploy the logging components, the existing PVCs are reused. This means any data or content that existed when you shutdown are still there when you redeploy. While not strictly a scale down/up process the result is the same. Perhaps this approach will work in your use-case as well.”

With the Viya deployment project, the deinstallation of cluster-logging and cluster-monitoring deletes everything including PV, PVCs and name spaces. 

Where are these files remove_logging_open.sh & deploy_logging_open.sh  located?

Thank you
Ira

**Comment by cumcke** [comment]
Hi Ira,

In the later releases of Viya 4 Monitoring for Kubernetes, the **deploy_logging_open.sh** and **remove_logging_open.sh** have been shortened to simply **deploy_logging.sh** and **remove_logging.sh**, respectively.  You can use those scripts to remove and redeploy the log monitoring components.

Regards,
Curtis

**Comment by irchum** [comment]
Hi Curtis,

Thank you. According to the PSD engineer, he cannot find these scripts in the environment, although Viya Monitoring has been deployed along with Viya using SAS Viya 4 Deployment project. According to the overview section (https://github.com/sassoftware/viya4-deployment), SAS Viya 4 Deployment can perform a list of tasks including Deploy SAS Viya Monitoring for Kubernetes. 

Is there any difference between deploying Viya Monitoring using SAS Viya 4 Deployment project and 
viya4-monitoring-kubernetes?

Should the engineer consider redeploy Viya Monitoring using https://github.com/sassoftware/viya4-monitoring-kubernetes?

Regards,
Ira

**Comment by gsmith-sas** [comment]
@irchum The Viya 4 Deployment project clones our project repo as part of the deployment process, runs the appropriate scripts and then cleans up after itself.   This means the copy of our project repo is not available after deployment.  It uses the same general process when removing things as well.  Given this behavior, if you want to continue using Viya 4 Deployment, you would need to (re)clone our project repo after the initial deployment process to have access to our scripts (including the `deploy_logging.sh` and `remove_logging.sh` scripts).  

However, one complication is that the Viya 4 Deployment project also removes the USER_DIR directory it used during the deployment process.  This is a directory containing files that tweak/customize the configuration of the our Viya 4 Monitoring project.  These files handle things like setting initial passwords (for Grafana and OpenSearch Dashboards) and configuring TLS and ingress.  You would need to manually recreate these files so that they can be consumed when you manually shutdown and restart the monitoring components.

Manually deploying the monitoring components (i.e. NOT using the Viya 4 Deployment project to deploy Viya 4 Monitoring) doesn't eliminate any of this but _may_ be easier to maintain since the initial deployment and subsequent restarts would all follow the same process and use the same files.

The process would be:

- Create cluster (possibly using the Viya 4 IAC for AWS)
- Deploy Viya 4 Monitoring
  - clone the Viya 4 Monitoring repository
  - create a USER_DIR directory with the proper structure
  - populate the USER_DIR with the appropriate files to customize the deployment as desired
  - run the `logging/bin/deploy_logging.sh` being careful to set the USER_DIR environment variable point to the USER_DIR directory created above
  - run the `monitoring/bin/deploy_monitoring.sh` script being careful to set the `USER_DIR` environment variable point to the USER_DIR directory created above
- Deploy SAS Viya (possibly using the Viya 4 Deployment project)
  - _Do **NOT**_ select the tasks/tags: **cluster-logging**  and **cluster-monitoring** (since you've already deployed those components above)
  - **_Do_** include the task/tag: **viya_monitoring**

On Friday evening (or whenever you want to "shutdown" everything), the process would be:

- Shutdown (or scale down) the SAS Viya components
- Shutdown the Viya 4 Monitoring components
  - Run `logging/bin/remove_logging.sh` script (again pointing to the USER_DIR created during the initial deployment process)
  - Run `monitoring/bin/remove_monitoring_cluster.sh` script (again pointing to the USER_DIR created during the initial deployment process)

On Monday morning (or whenever you want to "restart" everything), the process would be:

- "Restart" the Viya 4 Monitoring components
  - Run `logging/bin/deploy_logging.sh` script (again pointing to the USER_DIR created during the initial deployment process)
  - Run `monitoring/bin/deploy_monitoring_cluster.sh` script (again pointing to the USER_DIR created during the initial deployment process)
- Restart (scale up) SAS Viya components

It is **_critically important_** that the PVCs and namespace used by the Viya 4 Monitoring project are NOT deleted.  If either of those things happen, the previously collected data will be lost.

Information about the USER_DIR and customization process can be found in the [top-level README file](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/README.md#customization) in our repo with _important_ additional details in the [Pre-deployment chapter of the Log Monitoring documentation](https://go.documentation.sas.com/doc/en/sasadmincdc/v_031/callogging/p1j31coiuoun6mn1om73shkcq4ut.htm) and the [monitoring/README.md file](https://github.com/sassoftware/viya4-monitoring-kubernetes/blob/stable/monitoring/README.md) file.

**Comment by irchum** [comment]
@gsmith-sas Thank you for your detail answer.
If I understand correctly, Viya Monitoring cannot be deployed with Viya deployment project as it removes Viya monitoring project repo after the deployment. It would be good that Viya deployment project include new feature that keeps the Viya monitoring repo so that the appropriate scripts can be used rather than redeploying Viya Monitoring manually.

**Comment by gsmith-sas** [comment]
@irchum I'm going to close this issue since I think we've clarified how to handle things.  Feel free to reach out (either here or via internal e-mail/channels) if you need anything more.
