### ISSUE TITLE
Integration of Viya4 Monitoring with Google Cloud Managed Service for Prometheus

### ISSUE THREAD

**Issue by alessio4tech** [sassoftware/viya4-monitoring-kubernetes#399]
Google now recommends Google Cloud Managed Service for Prometheus to monitor GKE workloads. The Prometheus side-car and G​K​E workload metrics are both being deprecated. Is there a view as to whether Google Cloud Managed Service for Prometheus would work and potentially any gotchas to be aware of? Can it be considered a supported way of monitoring SAS workloads on GKE?

**Comment by gsmith-sas** [comment]
@alessio4tech Our team has not had a chance to investigate Google Cloud Managed Service for Prometheus yet, so we can't share any real insights on it yet.  Based on a _very_ quick scan of the doc, I suspect it should be compatible with the instrumentation built into SAS Viya that makes metrics available in Prometheus format.  I didn't have time to dig into how the SAS Viya-specific monitors (which tell Prometheus how to access that instrumentation layer in SAS Viya) would be used but assume it would be possible as well.

Our project, the Viya Monitoring for Kubernetes, is a monitoring solution SAS makes available to customers.  However, SAS customers are free to use whatever monitoring tools they choose to monitor their SAS Viya instances.  While SAS Technical Support cannot offer support for 3rd party monitoring solutions, it can open tracks to address issues identified in the metric instrumentation built into SAS Viya that are making it difficult to monitor SAS Viya.  

If you were asking if the Viya Monitoring project will support using Google Cloud Managed Service for Prometheus instead of our current approach of deploying our own instance of Prometheus, the answer is "not at this time".  However, it might be an option for us to consider in the future.

I hope that clarifies things a bit.

Regards,
Greg
