### ISSUE TITLE
Opensearch Dashboard 502 Bad gateway

### ISSUE THREAD

**Issue by Vergr0** [sassoftware/viya4-monitoring-kubernetes#551]
Hello,

I've deployed logging compontents using deploy_logging.sh script. I used user-values-opensearch.yaml and user-values-osd.yaml files from samples/azure-deployment directory to set path based ingress.

Deployment went fine, but when I try to access my.host/dashboards I get 502 Bad Gateway. There are no errors in osd pod logs. In ingress-nginx pod logs I see that when I try to access my.host/dashboards I get the following error:

![obraz](https://github.com/sassoftware/viya4-monitoring-kubernetes/assets/39826365/84b3a764-e204-494a-9bca-d070a10a8d7f)

Viya is deployed on AKS. Could you please help me resolve this issue?
Best Regards

**Comment by gsmith-sas** [comment]
@Vergr0 Thank you for reporting this issue;  I'm sorry to report that you have found a bug.   Evidently, the azure-deployment sample was not updated to reflect our recent change to enable TLS (and, HTTPS) by default.  Please use the user-values-opensearch.yaml and user-values-osd.yaml files in the samples/ingress/path-based-ingress sub-directory instead of the ones in the azure-deployment sample.  

If  you are using a custom storageClass for the OpenSearch PVCs (as recommended in the azure-deployment sample), you will need to copy the persistence stanza (i.e. the two lines setting the persistence and storageClass keys) from the azure-deployment/logging/user-values-opensearch.yaml file to your user-values-opensearch.yaml.

Thanks again for reporting this, please let us know if this resolves your issue.  We will correct the azure-deployment sample in the soon.

**Comment by Vergr0** [comment]
@gsmith-sas Thank you for quick reply. I followed your instructions and it worked, now I can access opensearch dashoboards without any issues. 

I'm closing the issue, thank you for help.
