### ISSUE TITLE
samples/azure-deployment default promethues URL for data source is wrong 

### ISSUE THREAD

**Issue by caili-zhang-sas** [sassoftware/viya4-monitoring-kubernetes#614]
I deploied monitoring tools using samples/azure-deployment.
Whent I login to grafana to check the connectivity, I found that prometheus is not connected.

I fixed this by editing [Connections] under [Data source] manually.
```
Wrong: http://v4m-prometheus:9090
Right: https://v4m-prometheus:9090/prometheus
```

However, after restarting the cluster, this value go back to the default one, which is wrong.
I dont know how to fix this from the yaml file, does anyone knows how to fix this permantly?

**Comment by gsmith-sas** [comment]
@caili-zhang-sas This problem can be fixed by setting the environment variable **MON_TLS_PATH_INGRESS** to '_true_' before re-running the `deploy_monitoring_cluster.sh` script.  The environment variable can be set by including it in the `monitoring/user.env` file in your USER_DIR directory.  That file should have been included in the sample but is not there currently.  Refer to the `ingress/path-based/monitoring/user.env` file to the structure and required content for this file.  We will revise the azure-deployment sample to include the missing file soon.

**Comment by gsmith-sas** [comment]
Thank you for reporting this issue (and #612).  Updates to the sample fixing both issues have been made and are now available on our 'main' branch.
