### ISSUE TITLE
ERROR There was an issue loading ingest pipeline into OpenSearch [503]

### ISSUE THREAD

**Issue by michburger** [sassoftware/viya4-monitoring-kubernetes#634]
Dear sassoftware support,

during installation I get this error message:

INFO Loading Content into OpenSearch
INFO The index management policy [viya_logs_idxmgmt_policy] already exist in OpenSearch; skipping load and using existing policy.
ERROR There was an issue loading ingest pipeline into OpenSearch [503]
ERROR Exiting script [deploy_logging.sh] due to an error executing the command [logging/bin/deploy_opensearch_content.sh].

Where can I find more details and how can I solve this?

**Comment by gsmith-sas** [comment]
@michburger Were you able to everything working or are you still having trouble?

**Comment by michburger** [comment]
Dear Greg,during my investigation, I found an out of space issue with the underlying database. Currently, I try to find out why old data was not deleted. I assume that these data are leftovers from previous viya logging setups.Many thanks for the hints!Michael Burger SoftMatch.net
-------- Ursprüngliche Nachricht --------Von: Greg Smith ***@***.***> Datum: 03.05.24  16:18  (GMT+01:00) An: sassoftware/viya4-monitoring-kubernetes ***@***.***> Cc: michburger ***@***.***>, Mention ***@***.***> Betreff: Re: [sassoftware/viya4-monitoring-kubernetes] ERROR There was an issue loading ingest pipeline into OpenSearch [503] (Issue #634) 
@michburger Were you able to everything working or are you still having trouble?

**Comment by gsmith-sas** [comment]
@michburger When OpenSearch runs out of space, it isn't able to do the index management processing that would (normally) delete "old" data and free up space.  The easiest (and most effective) solution at that point is to remove and redeploy after deleting the PVCs.  The logging/bin/remove_logging.sh script does NOT delete the OpenSearch PVCs by default.   However, you can have the script delete PVCs by setting the environment variable LOG_DELETE_PVCS_ON_REMOVE to 'true'.  

It is also a good idea to try and identify why you ran out of space.  For example, had you recently turned on a lot of DEBUG level messaging?  Did you deploy some new application onto the cluster that is especially verbose?  Are you aware of a problem that may have caused a spike in log volumes?  Was there especially heavy end-user activity?

If you determine that the spike in log message volume was a temporary event, you may decide to continue with the default size (30GB) for the OpenSearch PVCs.  However, if you are not sure or if you feel the end-user activity prior to the problem was "typical" for you environment, you may want to increase the size of these PVCs.  To increase the size of these PVCs before (re)deploying, you need to specify a larger value for the `persistences.size` key in the `logging/user-values-opensearch.yaml` file in your `$USER_DIR` directory.  More information about customizing your deployment of SAS Viya Monitoring can be found in the section [The Customization Process](https://go.documentation.sas.com/doc/en/obsrvcdc/v_002/obsrvdply/p09ed2sug992pdn1enejh2aca0jx.htm) in our documentation.  You may want review the sections [Adjust the Retention Period for Log Messages](https://go.documentation.sas.com/doc/en/obsrvcdc/v_002/obsrvdply/n1dwvmcsjvmw61n0zyiasrfae2yh.htm) and [Increase Storage for Log Messages](https://go.documentation.sas.com/doc/en/obsrvcdc/v_002/obsrvdply/n0h3y8378osja3n1aithq6gcb5gx.htm) as well.  The **Increase Storage for Log Message** section focuses on how to increase storage in a running system (rather than adjusting things during the pre-deployment phase).  I would encourage you to keep an eye on the size of the OpenSearch PVCs and make additional adjustments as-needed after you have things (re)deployed.
