### ISSUE TITLE
Dashboard Jobs

### ISSUE THREAD

**Issue by mauriziopinzi** [sassoftware/viya4-monitoring-kubernetes#657]
Hi,
dashboard "SAS Launched Jobs - User Activity" is only available if we use workload orchestrator?

**Comment by gsmith-sas** [comment]
Yes, that is correct.  The two Grafana dashboards that report metrics for "SAS Jobs" (i.e. SAS Launched Jobs - Node Activity and SAS Launched Jobs - User Activity) require that the SAS Viya component Workload Orchestrator.  This is because the Workload Orchestrator component makes the metrics about the job available to Prometheus (and Grafana) via the Prometheus Pushgateway.
